name: Setup depot tools
description: Setup depot tools
runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Cache depot_tools dependencies
      id: cache-depot-tools
      uses: actions/cache@v4
      with:
        path: depot_tools
        key: ${{ runner.os }}-depot-tools

    - name: Clone depot tools
      shell: bash
      run: |
        if [ ! -d "depot_tools" ]; then
          git clone --depth=1 --no-tags --single-branch https://chromium.googlesource.com/chromium/tools/depot_tools.git
        fi

    - name: Setup PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

    - name: Setup Windows ENV
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" >> $GITHUB_ENV
        fi

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global depot-tools.allowGlobalGitConfig true

    - name: Update depot_tools
      shell: bash
      run: update_depot_tools
